# server-b.yaml
apiVersion: v1
kind: Service
metadata:
  name: server-b
spec:
  clusterIP: None  # Headless service
  selector:
    app: server-b
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b
spec:
  replicas: 3  # Multiple replicas to demonstrate the concept
  selector:
    matchLabels:
      app: server-b
  template:
    metadata:
      labels:
        app: server-b
    spec:
      containers:
        - name: server-b
          image: server-b:latest
          imagePullPolicy: IfNotPresent  # Use for local images
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---